# Site settings
title: Max Prettyjohns
email: m@xprettyjohns.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, i'm Max and this is my personal blog and site, I will
  post any writing and interesting stuff here!
pygments: true
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ma.xprettyjohns.com" # the base hostname & protocol for your site
twitter_username: heshoots
github_username:  heshoots

# Build settings
markdown: kramdown
